[[redirects]]
  from = "/api-bapanas/*"
  to = "https://api-panelhargav2.badanpangan.go.id/:splat"
  status = 200
  force = true
  [redirects.headers]
    Origin = "https://panelharga.badanpangan.go.id"
    Referer = "https://panelharga.badanpangan.go.id/"
    Accept = "application/json"
    x-api-key = "zHWbt7U2qvPoUDkiUgvnOqYrtj3zClR7unnH2G4apE7HcMV4QyNC6BSD0yV3uvSHqS91TxwE8aMDTiCznmGceEX3zQmO1Xwq7TJblotIt2CpwvK6YjRKDJwcgMJwav9p4RshM3nfuFyurSQQv9BhueMJ0HJ778oD"
    User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
