[[redirects]]
  from = "/api-bapanas/*"
  to = "https://api-panelhargav2.badanpangan.go.id/:splat"
  status = 200
  force = true
  [redirects.headers]
    Origin = "https://panelharga.badanpangan.go.id"
    Referer = "https://panelharga.badanpangan.go.id/"
    User-Agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
